SETTINGS_SCHEMA = [
    {"group": "Zombies / Zombies", "settings": [
        {"key": "Zombies", "label": "Population / Bevölkerung", "type": "select", "file": "sandbox",
         "options": {"1": "Insane", "2": "Very High", "3": "High", "4": "Normal", "5": "Low"}, "default": 4},
        {"key": "Distribution", "label": "Distribution / Verteilung", "type": "select", "file": "sandbox",
         "options": {"1": "Urban Focused", "2": "Uniform"}, "default": 1},
        {"key": "ZombieSpeed", "label": "Speed / Geschwindigkeit", "type": "select", "file": "sandbox",
         "options": {"1": "Sprinter", "2": "Fast Shambler", "3": "Shambler"}, "default": 2},
        {"key": "ZombieStrength", "label": "Strength / Stärke", "type": "select", "file": "sandbox",
         "options": {"1": "Superhuman", "2": "Normal", "3": "Weak"}, "default": 2},
        {"key": "ZombieToughness", "label": "Toughness / Zähigkeit", "type": "select", "file": "sandbox",
         "options": {"1": "Tough", "2": "Normal", "3": "Fragile"}, "default": 2},
        {"key": "ZombieCognition", "label": "Cognition / Intelligenz", "type": "select", "file": "sandbox",
         "options": {"1": "Navigate + Doors", "2": "Navigate", "3": "Basic"}, "default": 3},
        {"key": "ZombieMemory", "label": "Memory / Gedächtnis", "type": "select", "file": "sandbox",
         "options": {"1": "Long", "2": "Normal", "3": "Short", "4": "None"}, "default": 2},
        {"key": "ZombieSight", "label": "Sight / Sicht", "type": "select", "file": "sandbox",
         "options": {"1": "Eagle", "2": "Normal", "3": "Poor"}, "default": 2},
        {"key": "ZombieHearing", "label": "Hearing / Gehör", "type": "select", "file": "sandbox",
         "options": {"1": "Pinpoint", "2": "Normal", "3": "Poor"}, "default": 2},
        {"key": "ZombieSmell", "label": "Smell / Geruch", "type": "select", "file": "sandbox",
         "options": {"1": "Bloodhound", "2": "Normal", "3": "Poor"}, "default": 2},
        {"key": "ZombieRespawn", "label": "Respawn", "type": "number", "file": "sandbox", "default": 0},
        {"key": "RallyGroupSize", "label": "Rally Group Size / Hordengröße", "type": "number", "file": "sandbox", "default": 20},
    ]},
    {"group": "Infection / Infektion", "settings": [
        {"key": "Transmission", "label": "Transmission / Übertragung", "type": "select", "file": "sandbox",
         "options": {"1": "Blood + Saliva", "2": "Saliva Only", "3": "Everyone Infected", "4": "None"}, "default": 1},
        {"key": "Mortality", "label": "Mortality / Sterblichkeit", "type": "select", "file": "sandbox",
         "options": {"1": "Instant", "2": "0-30s", "3": "0-1min", "4": "0-12h", "5": "2-3 days", "6": "1-2 weeks"}, "default": 5},
        {"key": "Infection", "label": "Wound Infection / Wundinfektion", "type": "select", "file": "sandbox",
         "options": {"1": "None", "2": "Normal"}, "default": 2},
        {"key": "InjurySeverity", "label": "Injury Severity / Verletzungsschwere", "type": "select", "file": "sandbox",
         "options": {"1": "Low", "2": "Normal", "3": "High"}, "default": 2},
    ]},
    {"group": "Loot / Beute", "settings": [
        {"key": "FoodLoot", "label": "Food / Essen", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "WeaponLoot", "label": "Weapons / Waffen", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "MedicalLoot", "label": "Medical / Medizin", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "OtherLoot", "label": "Other / Sonstiges", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "CannedFoodLoot", "label": "Canned Food / Konserven", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "LiteratureLoot", "label": "Literature / Literatur", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "SurvivalGearsLoot", "label": "Survival Gear / Überlebensausrüstung", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
        {"key": "MechanicsLoot", "label": "Mechanics / Mechanik", "type": "select", "file": "sandbox",
         "options": {"1": "Very Rare", "2": "Rare", "3": "Normal", "4": "Common", "5": "Abundant"}, "default": 3},
    ]},
    {"group": "Utilities / Versorgung", "settings": [
        {"key": "WaterShut", "label": "Water Shutoff / Wasserabschaltung", "type": "select", "file": "sandbox",
         "options": {"1": "0-30 Days", "2": "0-2 Months", "3": "0-6 Months", "4": "0-12 Months", "5": "2-6 Months", "6": "6-12 Months", "7": "6-12 Months (max)"}, "default": 2},
        {"key": "WaterShutModifier", "label": "Water Shutoff Modifier / Wasser-Modifier", "type": "number", "file": "sandbox", "default": 14},
        {"key": "ElecShut", "label": "Electricity Shutoff / Stromabschaltung", "type": "select", "file": "sandbox",
         "options": {"1": "0-30 Days", "2": "0-2 Months", "3": "0-6 Months", "4": "0-12 Months", "5": "2-6 Months", "6": "6-12 Months", "7": "6-12 Months (max)"}, "default": 2},
        {"key": "ElecShutModifier", "label": "Electricity Modifier / Strom-Modifier", "type": "number", "file": "sandbox", "default": 14},
    ]},
    {"group": "World / Welt", "settings": [
        {"key": "DayLength", "label": "Day Length / Tageslänge", "type": "select", "file": "sandbox",
         "options": {"1": "15 min", "2": "30 min", "3": "1 hr", "4": "2 hr", "5": "3 hr"}, "default": 3},
        {"key": "Temperature", "label": "Temperature / Temperatur", "type": "select", "file": "sandbox",
         "options": {"1": "Very Cold", "2": "Cold", "3": "Normal", "4": "Warm"}, "default": 3},
        {"key": "Rain", "label": "Rain / Regen", "type": "select", "file": "sandbox",
         "options": {"1": "Very Dry", "2": "Dry", "3": "Normal", "4": "Rainy", "5": "Very Rainy"}, "default": 3},
        {"key": "ErosionSpeed", "label": "Erosion Speed / Erosionsrate", "type": "select", "file": "sandbox",
         "options": {"1": "Very Fast", "2": "Fast", "3": "Normal", "4": "Slow", "5": "Very Slow"}, "default": 3},
        {"key": "FarmingSpeed", "label": "Farming Speed / Farmgeschwindigkeit", "type": "select", "file": "sandbox",
         "options": {"1": "Very Fast", "2": "Fast", "3": "Normal", "4": "Slow", "5": "Very Slow"}, "default": 3},
        {"key": "NatureAbundance", "label": "Nature Abundance / Naturvorkommen", "type": "select", "file": "sandbox",
         "options": {"1": "Very Poor", "2": "Poor", "3": "Normal", "4": "Abundant", "5": "Very Abundant"}, "default": 3},
        {"key": "Alarm", "label": "Alarm Frequency / Alarm-Häufigkeit", "type": "select", "file": "sandbox",
         "options": {"1": "Never", "2": "Very Rare", "3": "Rare", "4": "Sometimes", "5": "Often", "6": "Very Often"}, "default": 4},
        {"key": "LockedHouses", "label": "Locked Houses / Verschlossene Häuser", "type": "select", "file": "sandbox",
         "options": {"1": "Never", "2": "Very Rare", "3": "Rare", "4": "Sometimes", "5": "Often", "6": "Very Often"}, "default": 4},
        {"key": "Meta", "label": "Meta Events (Helicopter) / Meta-Events", "type": "select", "file": "sandbox",
         "options": {"1": "Never", "2": "Sometimes", "3": "Often"}, "default": 2},
    ]},
    {"group": "Vehicles / Fahrzeuge", "settings": [
        {"key": "EnableVehicles", "label": "Enable / Aktiviert", "type": "boolean", "file": "sandbox", "default": True},
        {"key": "CarSpawnRate", "label": "Spawn Rate / Spawnrate", "type": "select", "file": "sandbox",
         "options": {"1": "None", "2": "Very Low", "3": "Low", "4": "Normal"}, "default": 4},
        {"key": "ChanceHasGas", "label": "Chance Has Gas / Benzinchance (%)", "type": "number", "file": "sandbox", "default": 50},
        {"key": "InitialGas", "label": "Initial Gas / Starttankfüllung", "type": "select", "file": "sandbox",
         "options": {"1": "Empty", "2": "Low", "3": "Normal", "4": "High", "5": "Full"}, "default": 3},
        {"key": "CarGasConsumption", "label": "Gas Consumption / Verbrauch", "type": "number", "file": "sandbox", "default": 1.0},
        {"key": "CarGeneralCondition", "label": "General Condition / Zustand", "type": "select", "file": "sandbox",
         "options": {"1": "Very Low", "2": "Low", "3": "Normal", "4": "High", "5": "Very High"}, "default": 3},
    ]},
    {"group": "XP & Skills / XP & Fähigkeiten", "settings": [
        {"key": "XPMultiplier", "label": "XP Multiplier / XP-Multiplikator", "type": "number", "file": "sandbox", "default": 1.0},
        {"key": "StatsDecrease", "label": "Stats Decrease / Statusverfall", "type": "select", "file": "sandbox",
         "options": {"1": "Very Fast", "2": "Fast", "3": "Normal", "4": "Slow", "5": "Very Slow"}, "default": 3},
    ]},
    {"group": "Player / Spieler", "settings": [
        {"key": "PlayerBuildingHealth", "label": "Building Health / Gebäude-HP", "type": "select", "file": "sandbox",
         "options": {"1": "Very Low", "2": "Low", "3": "Normal", "4": "High", "5": "Very High"}, "default": 3},
        {"key": "MultiHitZombies", "label": "Multi-Hit / Mehrfachtreffer", "type": "boolean", "file": "sandbox", "default": False},
        {"key": "RearVulnerability", "label": "Rear Vulnerability / Rückenanfälligkeit", "type": "boolean", "file": "sandbox", "default": True},
        {"key": "ToolDurability", "label": "Tool Durability / Werkzeug-Haltbarkeit", "type": "select", "file": "sandbox",
         "options": {"1": "Very Low", "2": "Low", "3": "Normal", "4": "High", "5": "Very High"}, "default": 3},
    ]},
    {"group": "Multiplayer / Mehrspieler", "settings": [
        {"key": "PVP", "label": "PVP", "type": "boolean", "file": "sandbox", "default": True},
        {"key": "MapAllKnown", "label": "Map Known / Karte bekannt", "type": "boolean", "file": "sandbox", "default": False},
        {"key": "SleepAllowed", "label": "Sleep Allowed / Schlafen erlaubt", "type": "boolean", "file": "ini", "default": False},
        {"key": "SleepNeeded", "label": "Sleep Needed / Schlafen nötig", "type": "boolean", "file": "ini", "default": False},
        {"key": "PauseEmpty", "label": "Pause When Empty / Pause bei leerem Server", "type": "boolean", "file": "ini", "default": False},
        {"key": "SafehouseDaySurvivedToClaim", "label": "Days to Claim Safehouse / Tage für Safehouse", "type": "number", "file": "ini", "default": 0},
        {"key": "SafehouseAllowRespawn", "label": "Safehouse Respawn", "type": "boolean", "file": "ini", "default": False},
        {"key": "SafehouseAllowFire", "label": "Safehouse Fire / Safehouse-Feuer", "type": "boolean", "file": "ini", "default": True},
        {"key": "AnnounceDeath", "label": "Announce Death / Tod ankündigen", "type": "boolean", "file": "sandbox", "default": False},
    ]},
    {"group": "Server", "settings": [
        {"key": "FastReadMultiplier", "label": "Book Read Speed / Lese-Geschwindigkeit (min/page)", "type": "number", "file": "ini", "default": 1.0},
        {"key": "SpawnPoint", "label": "Spawn Point / Spawnpunkt (x,y,z)", "type": "text", "file": "ini", "default": ""},
        {"key": "SpawnItems", "label": "Spawn Items / Start-Items (;-getrennt)", "type": "text", "file": "ini", "default": ""},
    ]},
]
