import json
import os

from config import STATE_FILE, MODS_FILE


def load_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE) as f:
            state = json.load(f)
        state.setdefault("users", {})
        return state
    return {"mods": [], "discord_thread_id": None, "users": {}}


def save_state(state):
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)


def sync_mods_txt(state):
    with open(MODS_FILE, "w") as f:
        f.write("# Auto-generated by ZombiRadar — do not edit manually\n")
        for mod in state["mods"]:
            if mod["status"] == "approved":
                f.write(f"{mod['workshop_id']}\n")
