#!/usr/bin/env python3
"""PZ Mod Manager with Discord OAuth, voting, staging, and Discord thread integration."""

import json
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from http.server import HTTPServer, BaseHTTPRequestHandler
from http.cookies import SimpleCookie
from hashlib import sha256

PORT = int(os.environ.get("PORT", "8080"))
MODS_FILE = os.environ.get("MODS_FILE", "/data/mods.txt")
STATE_FILE = os.environ.get("STATE_FILE", "/data/state.json")

DISCORD_TOKEN = os.environ.get("DISCORD_TOKEN", "")
DISCORD_CHANNEL_ID = os.environ.get("DISCORD_CHANNEL_ID", "")
DISCORD_CLIENT_ID = os.environ.get("DISCORD_CLIENT_ID", "")
DISCORD_CLIENT_SECRET = os.environ.get("DISCORD_CLIENT_SECRET", "")
MOD_MANAGER_URL = os.environ.get("MOD_MANAGER_URL", "http://localhost:8080").rstrip("/")
MOD_MANAGER_ADMINS = set(
    a.strip() for a in os.environ.get("MOD_MANAGER_ADMINS", "").split(",") if a.strip()
)

OAUTH_REDIRECT_URI = f"{MOD_MANAGER_URL}/api/callback"
OAUTH_AUTHORIZE_URL = (
    f"https://discord.com/oauth2/authorize?client_id={DISCORD_CLIENT_ID}"
    f"&redirect_uri={urllib.parse.quote(OAUTH_REDIRECT_URI)}"
    f"&response_type=code&scope=identify"
)

SESSIONS = {}


def load_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE) as f:
            return json.load(f)
    return {"mods": [], "discord_thread_id": None}


def save_state(state):
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)


def sync_mods_txt(state):
    with open(MODS_FILE, "w") as f:
        f.write("# Auto-generated by mod-manager — do not edit manually\n")
        for mod in state["mods"]:
            if mod["status"] == "approved":
                f.write(f"{mod['workshop_id']}\n")


def fetch_workshop_title(workshop_id):
    try:
        url = f"https://steamcommunity.com/sharedfiles/filedetails/?id={workshop_id}"
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=5) as resp:
            html = resp.read().decode("utf-8", errors="replace")
        m = re.search(r'<div class="workshopItemTitle">([^<]+)</div>', html)
        return m.group(1).strip() if m else None
    except Exception:
        return None


def discord_api(method, path, body=None, token=None, content_type="application/json"):
    url = f"https://discord.com/api/v10{path}"
    if content_type == "application/json":
        data = json.dumps(body).encode() if body else None
    else:
        data = urllib.parse.urlencode(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bot {DISCORD_TOKEN}" if not token else f"Bearer {token}",
        "Content-Type": content_type,
        "User-Agent": "PZ-ModManager/1.0",
    })
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except Exception as e:
        print(f"mod-manager: discord api error: {e}")
        return None


def exchange_code(code):
    data = urllib.parse.urlencode({
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": OAUTH_REDIRECT_URI,
        "client_id": DISCORD_CLIENT_ID,
        "client_secret": DISCORD_CLIENT_SECRET,
    }).encode()
    req = urllib.request.Request(
        "https://discord.com/api/v10/oauth2/token",
        data=data,
        method="POST",
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": "PZ-ModManager/1.0",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"mod-manager: oauth token exchange error: {e.code} {body}")
        return None
    except Exception as e:
        print(f"mod-manager: oauth token exchange error: {e}")
        return None


def fetch_discord_user(access_token):
    return discord_api("GET", "/users/@me", token=access_token)


def ensure_discord_thread(state):
    if state.get("discord_thread_id"):
        return state["discord_thread_id"]
    if not DISCORD_TOKEN or not DISCORD_CHANNEL_ID:
        return None
    result = discord_api("POST", f"/channels/{DISCORD_CHANNEL_ID}/threads", {
        "name": "Mod-Vorschläge",
        "type": 11,
        "auto_archive_duration": 10080,
    })
    if result and "id" in result:
        state["discord_thread_id"] = result["id"]
        save_state(state)
        return result["id"]
    return None


def post_mod_to_discord(state, mod, action="suggested"):
    thread_id = ensure_discord_thread(state)
    if not thread_id:
        return
    title = mod.get("title") or mod["workshop_id"]
    url = f"https://steamcommunity.com/sharedfiles/filedetails/?id={mod['workshop_id']}"
    votes = mod.get("votes", {})
    if isinstance(votes, dict):
        ups = sum(1 for v in votes.values() if v > 0)
        downs = sum(1 for v in votes.values() if v < 0)
        score = ups - downs
        vote_count = f"+{score}" if score > 0 else str(score)
        voters = f"\U0001F44D {ups} \U0001F44E {downs}"
    else:
        vote_count = len(votes)
        voters = ", ".join(votes) if votes else "keine"

    messages = {
        "suggested": (
            f":new: **Neuer Mod-Vorschlag** von **{mod.get('suggested_by', '?')}**\n"
            f"**{title}**\n{url}\nStimmen: {vote_count} ({voters})"
        ),
        "approved": (
            f":white_check_mark: **Mod genehmigt!**\n"
            f"**{title}**\n{url}\nStimmen: {vote_count} ({voters})\n"
            f"*Wird beim nächsten Server-Neustart geladen.*"
        ),
        "rejected": (
            f":x: **Mod abgelehnt**\n~~{title}~~\n{url}\nStimmen: {vote_count} ({voters})"
        ),
        "voted": (
            f":thumbsup: **Mod-Vorschlag**\n"
            f"**{title}**\n{url}\nStimmen: {vote_count} ({voters})"
        ),
    }
    content = messages.get(action)
    if not content:
        return

    msg_id = mod.get("discord_msg_id")
    if msg_id:
        discord_api("PATCH", f"/channels/{thread_id}/messages/{msg_id}", {"content": content})
    else:
        result = discord_api("POST", f"/channels/{thread_id}/messages", {"content": content})
        if result and "id" in result:
            mod["discord_msg_id"] = result["id"]
            save_state(state)
            if action == "suggested":
                r1 = discord_api("PUT", f"/channels/{thread_id}/messages/{result['id']}/reactions/%F0%9F%91%8D/%40me")
                print(f"mod-manager: seed 👍: {r1}")
                time.sleep(0.5)
                r2 = discord_api("PUT", f"/channels/{thread_id}/messages/{result['id']}/reactions/%F0%9F%91%8E/%40me")
                print(f"mod-manager: seed 👎: {r2}")


def fetch_discord_voters(thread_id, msg_id):
    if not thread_id or not msg_id:
        return set()
    result = discord_api("GET", f"/channels/{thread_id}/messages/{msg_id}/reactions/%F0%9F%91%8D")
    if not result or not isinstance(result, list):
        return set()
    return {u["id"] for u in result if u["id"] != DISCORD_CLIENT_ID}


_discord_votes_cache = {}
_discord_votes_cache_time = 0
CACHE_TTL = 60

def get_all_discord_votes(state):
    global _discord_votes_cache, _discord_votes_cache_time
    if time.time() - _discord_votes_cache_time < CACHE_TTL:
        return _discord_votes_cache
    thread_id = state.get("discord_thread_id")
    if not thread_id:
        return {}
    msg_ids = [
        mod.get("discord_msg_id")
        for mod in state["mods"]
        if mod.get("discord_msg_id")
    ]
    if not msg_ids:
        return {}
    result = {}
    with ThreadPoolExecutor(max_workers=5) as pool:
        futures = {pool.submit(fetch_discord_voters, thread_id, mid): mid for mid in msg_ids}
        for future in futures:
            result[futures[future]] = future.result()
    _discord_votes_cache = result
    _discord_votes_cache_time = time.time()
    return result


def make_session(discord_user):
    user_id = discord_user["id"]
    username = discord_user.get("global_name") or discord_user["username"]
    avatar = discord_user.get("avatar")
    avatar_url = (
        f"https://cdn.discordapp.com/avatars/{user_id}/{avatar}.png"
        if avatar else None
    )
    role = "admin" if user_id in MOD_MANAGER_ADMINS else "user"
    token = sha256(f"{user_id}{time.time()}{os.urandom(16).hex()}".encode()).hexdigest()[:32]
    SESSIONS[token] = {
        "discord_id": user_id,
        "username": username,
        "avatar_url": avatar_url,
        "role": role,
    }
    return token


HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PZ Mod Manager</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #1a1a2e; color: #e0e0e0; min-height: 100vh; padding: 2rem; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { color: #e94560; margin-bottom: 0.5rem; }
  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem; }
  .header-left h1 { margin-bottom: 0.25rem; }
  .subtitle { color: #888; }
  .user-info { display: flex; align-items: center; gap: 0.75rem; color: #888; font-size: 0.9rem; }
  .user-info strong { color: #e0e0e0; }
  .user-info a { color: #e94560; text-decoration: none; }
  .avatar { width: 32px; height: 32px; border-radius: 50%; }
  .card { background: #16213e; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
  .card h2 { color: #e94560; margin-bottom: 1rem; font-size: 1.1rem; }
  .form-row { display: flex; gap: 0.75rem; margin-bottom: 0.75rem; flex-wrap: wrap; }
  input[type="text"] { flex: 1; min-width: 200px; padding: 0.6rem 0.8rem; border: 1px solid #333;
                        border-radius: 4px; background: #0f3460; color: #e0e0e0; font-size: 0.95rem; }
  input::placeholder { color: #666; }
  input:focus { outline: none; border-color: #e94560; }
  button { padding: 0.6rem 1.2rem; border: none; border-radius: 4px; cursor: pointer;
           font-size: 0.95rem; font-weight: 500; transition: opacity 0.2s; }
  button:hover { opacity: 0.85; }
  .btn-primary { background: #e94560; color: white; }
  .btn-discord { background: #5865F2; color: white; display: flex; align-items: center;
                 gap: 0.5rem; font-size: 1rem; padding: 0.8rem 1.5rem; width: 100%;
                 justify-content: center; }
  .btn-vote { background: #0f3460; color: #4caf50; border: 1px solid #333; }
  .btn-vote.voted { background: #1a3a1a; border-color: #4caf50; }
  .btn-approve { background: #1a3a1a; color: #4caf50; }
  .btn-reject { background: #3a1a1a; color: #e94560; }
  .btn-sm { padding: 0.4rem 0.8rem; font-size: 0.85rem; }
  .mod-item { display: flex; justify-content: space-between; align-items: center; padding: 0.8rem;
              border-bottom: 1px solid #222; gap: 1rem; }
  .mod-item:last-child { border-bottom: none; }
  .mod-info { flex: 1; min-width: 0; }
  .mod-title { color: #e0e0e0; font-weight: 500; }
  .mod-title a { color: #5ba4e6; text-decoration: none; }
  .mod-title a:hover { text-decoration: underline; }
  .mod-meta { color: #888; font-size: 0.85rem; margin-top: 0.25rem; }
  .mod-actions { display: flex; gap: 0.5rem; flex-shrink: 0; align-items: center; }
  .vote-box { display: flex; flex-direction: column; align-items: center; gap: 0.2rem; min-width: 3rem; }
  .score { font-weight: 700; font-size: 1.1rem; }
  .score-pos { color: #4caf50; }
  .score-neg { color: #e94560; }
  .score-zero { color: #888; }
  .btn-up, .btn-down { background: #0f3460; border: 1px solid #333; color: #888; padding: 0.2rem 0.5rem;
                        font-size: 1rem; border-radius: 4px; cursor: pointer; transition: all 0.15s; }
  .btn-up:hover { border-color: #4caf50; color: #4caf50; }
  .btn-down:hover { border-color: #e94560; color: #e94560; }
  .btn-up.active { background: #1a3a1a; border-color: #4caf50; color: #4caf50; }
  .btn-down.active { background: #3a1a1a; border-color: #e94560; color: #e94560; }
  .btn-up:disabled, .btn-down:disabled { opacity: 0.5; cursor: default; }
  .btn-delete { background: none; border: 1px solid #333; color: #666; padding: 0.3rem 0.5rem; }
  .btn-delete:hover { border-color: #e94560; color: #e94560; }
  .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 3px; font-size: 0.75rem;
           font-weight: 600; text-transform: uppercase; }
  .badge-suggested { background: #0f3460; color: #5ba4e6; }
  .badge-approved { background: #1a3a1a; color: #4caf50; }
  .badge-rejected { background: #3a1a1a; color: #e94560; }
  .empty { color: #666; font-style: italic; padding: 1rem; }
  .notice { background: #0f3460; border-left: 3px solid #e94560; padding: 0.8rem 1rem;
            border-radius: 0 4px 4px 0; margin-bottom: 1.5rem; font-size: 0.9rem; color: #aaa; }
  .status { padding: 0.5rem; margin-top: 0.5rem; border-radius: 4px; font-size: 0.9rem; display: none; }
  .status.ok { display: block; background: #1a3a1a; color: #4caf50; }
  .status.err { display: block; background: #3a1a1a; color: #e94560; }
  .login-card { max-width: 400px; margin: 4rem auto; text-align: center; }
  .login-card h2 { margin-bottom: 1.5rem; }
  .loading { color: #888; font-style: italic; }
  .discord-icon { width: 20px; height: 20px; }
</style>
</head>
<body>
<div class="container" id="app"></div>

<script>
let currentUser = null;

async function api(method, path, body) {
  const opts = { method, headers: { "Content-Type": "application/json" } };
  if (body) opts.body = JSON.stringify(body);
  const r = await fetch(path, opts);
  if (r.status === 401) { currentUser = null; render(); return null; }
  return r.json();
}

function extractId(input) {
  const m = input.match(/id=(\\d+)/);
  return m ? m[1] : input.trim();
}

async function checkSession() {
  const res = await api("GET", "/api/session");
  if (res && res.ok) currentUser = res;
  render();
}

function renderLogin() {
  document.getElementById("app").innerHTML = `
    <div class="login-card card">
      <h2>PZ Mod Manager</h2>
      <p class="subtitle" style="margin-bottom:1.5rem">Melde dich mit Discord an, um Mods vorzuschlagen und abzustimmen.</p>
      <a href="/api/login" style="text-decoration:none">
        <button class="btn-discord">
          <svg class="discord-icon" viewBox="0 0 24 24" fill="white"><path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057a.082.082 0 0 0 .031.057 19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028c.462-.63.874-1.295 1.226-1.994a.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03z"/></svg>
          Login mit Discord
        </button>
      </a>
    </div>`;
}

async function render() {
  if (!currentUser) { renderLogin(); return; }
  const mods = await api("GET", "/api/mods");
  if (!mods) return;

  const isAdmin = currentUser.role === "admin";
  const suggested = mods.filter(m => m.status === "suggested");
  const approved = mods.filter(m => m.status === "approved");
  const rejected = mods.filter(m => m.status === "rejected");

  const avatarHtml = currentUser.avatar_url
    ? '<img class="avatar" src="' + currentUser.avatar_url + '">'
    : '';

  let html = `
    <div class="header">
      <div class="header-left"><h1>PZ Mod Manager</h1><p class="subtitle">Mods vorschlagen, abstimmen & genehmigen</p></div>
      <div class="user-info">${avatarHtml}<strong>${currentUser.username}</strong> (${isAdmin ? "Admin" : "Spieler"})
        <a href="/api/logout">Logout</a></div>
    </div>
    <div class="notice">Genehmigte Mods werden beim nächsten Server-Neustart geladen.</div>
    <div class="card">
      <h2>Mod vorschlagen</h2>
      <div class="form-row">
        <input type="text" id="workshop-id" placeholder="Steam Workshop URL oder ID"
          onkeydown="if(event.key==='Enter')suggest()">
        <button class="btn-primary" onclick="suggest()">Vorschlagen</button>
      </div>
      <div id="add-status" class="status"></div>
    </div>`;

  if (suggested.length) {
    html += '<div class="card"><h2>Vorschläge (' + suggested.length + ')</h2>';
    html += renderModList(suggested, mods, isAdmin);
    html += '</div>';
  }
  if (approved.length) {
    html += '<div class="card"><h2>Genehmigte Mods (' + approved.length + ')</h2>';
    html += renderModList(approved, mods, isAdmin);
    html += '</div>';
  }
  if (rejected.length) {
    html += '<div class="card"><h2>Abgelehnt (' + rejected.length + ')</h2>';
    html += renderModList(rejected, mods, isAdmin);
    html += '</div>';
  }
  if (!suggested.length && !approved.length && !rejected.length) {
    html += '<div class="card"><p class="empty">Noch keine Mods vorgeschlagen.</p></div>';
  }

  document.getElementById("app").innerHTML = html;

  mods.forEach((m, i) => {
    if (!m.title) {
      api("GET", "/api/lookup/" + m.workshop_id).then(data => {
        if (data && data.title) {
          const el = document.querySelector('[data-wid="' + m.workshop_id + '"] .mod-title-text');
          if (el) el.textContent = data.title;
        }
      });
    }
  });
}

function renderModList(list, allMods, isAdmin) {
  return list.map(m => {
    const idx = allMods.indexOf(m);
    const votes = m.votes || {};
    const myVote = votes[currentUser.username] || 0;
    const hasVotedDiscord = m.voted_on_discord;
    const discordVotes = m.discord_vote_count || 0;
    const ups = Object.values(votes).filter(v => v > 0).length + discordVotes;
    const downs = Object.values(votes).filter(v => v < 0).length;
    const score = ups - downs;
    const url = "https://steamcommunity.com/sharedfiles/filedetails/?id=" + m.workshop_id;
    const title = m.title || m.workshop_id;
    const badge = m.status === "approved" ? "approved" : m.status === "rejected" ? "rejected" : "suggested";
    const badgeText = m.status === "approved" ? "Genehmigt" : m.status === "rejected" ? "Abgelehnt" : "Vorschlag";

    let voteButtons = "";
    if (m.status === "suggested") {
      if (hasVotedDiscord) {
        voteButtons = '<button class="btn-up btn-sm active" disabled title="Auf Discord abgestimmt">\\u{1F44D}</button>' +
          '<button class="btn-down btn-sm" disabled>\\u{1F44E}</button>';
      } else {
        const upActive = myVote === 1 ? " active" : "";
        const downActive = myVote === -1 ? " active" : "";
        voteButtons = '<button class="btn-up btn-sm' + upActive + '" onclick="vote(' + idx + ',1)">\\u{1F44D}</button>' +
          '<button class="btn-down btn-sm' + downActive + '" onclick="vote(' + idx + ',-1)">\\u{1F44E}</button>';
      }
    }

    let adminButtons = "";
    if (m.status === "suggested" && isAdmin) {
      adminButtons = '<button class="btn-approve btn-sm" onclick="stage(' + idx + ',\\'approved\\')">Genehmigen</button>' +
        '<button class="btn-reject btn-sm" onclick="stage(' + idx + ',\\'rejected\\')">Ablehnen</button>';
    }
    if (isAdmin && m.status === "approved") {
      adminButtons = '<button class="btn-reject btn-sm" onclick="stage(' + idx + ',\\'rejected\\')">Entfernen</button>';
    }
    if (isAdmin && m.status === "rejected") {
      adminButtons = '<button class="btn-approve btn-sm" onclick="stage(' + idx + ',\\'approved\\')">Genehmigen</button>';
    }
    if (isAdmin) {
      adminButtons += '<button class="btn-delete btn-sm" onclick="deleteMod(' + idx + ')">\\u{1F5D1}</button>';
    }

    const scoreClass = score > 0 ? "score-pos" : score < 0 ? "score-neg" : "score-zero";
    const upVoters = Object.entries(votes).filter(([k,v]) => v > 0).map(([k]) => k);
    const downVoters = Object.entries(votes).filter(([k,v]) => v < 0).map(([k]) => k);
    let voterLine = "";
    if (upVoters.length) voterLine += '\\u{1F44D} ' + upVoters.join(", ");
    if (upVoters.length && downVoters.length) voterLine += "  ";
    if (downVoters.length) voterLine += '\\u{1F44E} ' + downVoters.join(", ");
    if (discordVotes) voterLine += (voterLine ? "  " : "") + '(+' + discordVotes + ' via Discord)';
    if (!voterLine) voterLine = "noch keine Stimmen";

    return '<div class="mod-item" data-wid="' + m.workshop_id + '">' +
      '<div class="vote-box">' + voteButtons +
        '<div class="score ' + scoreClass + '">' + (score > 0 ? "+" : "") + score + '</div></div>' +
      '<div class="mod-info">' +
        '<div class="mod-title"><a href="' + url + '" target="_blank" class="mod-title-text">' + title + '</a> ' +
          '<span class="badge badge-' + badge + '">' + badgeText + '</span></div>' +
        '<div class="mod-meta">Vorgeschlagen von ' + (m.suggested_by || "?") + '</div>' +
        '<div class="mod-meta">' + voterLine + '</div>' +
      '</div>' +
      '<div class="mod-actions">' + adminButtons + '</div></div>';
  }).join("");
}

async function suggest() {
  const wid = extractId(document.getElementById("workshop-id").value);
  if (!wid) return;
  const st = document.getElementById("add-status");
  const res = await api("POST", "/api/mods", { workshop_id: wid });
  if (res && res.ok) {
    st.className = "status ok"; st.textContent = "Vorschlag eingereicht!";
    document.getElementById("workshop-id").value = "";
    render();
  } else {
    st.className = "status err"; st.textContent = (res && res.error) || "Fehler";
  }
  setTimeout(() => { st.className = "status"; }, 3000);
}

async function vote(idx, value) {
  await api("POST", "/api/mods/" + idx + "/vote", { value: value });
  render();
}

async function stage(idx, status) {
  await api("POST", "/api/mods/" + idx + "/stage", { status: status });
  render();
}

async function deleteMod(idx) {
  if (!confirm("Eintrag endgültig löschen?")) return;
  await api("POST", "/api/mods/" + idx + "/stage", { status: "deleted" });
  render();
}

checkSession();
</script>
</body>
</html>"""


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass

    def get_session(self):
        cookie = SimpleCookie(self.headers.get("Cookie", ""))
        token = cookie.get("session")
        if token and token.value in SESSIONS:
            return SESSIONS[token.value]
        return None

    def require_auth(self):
        session = self.get_session()
        if not session:
            self.send_json({"error": "unauthorized"}, 401)
        return session

    def send_json(self, data, code=200, headers=None):
        body = json.dumps(data).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        for k, v in (headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def send_redirect(self, url, headers=None):
        self.send_response(302)
        self.send_header("Location", url)
        for k, v in (headers or {}).items():
            self.send_header(k, v)
        self.end_headers()

    def send_html(self):
        body = HTML.encode()
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def read_body(self):
        length = int(self.headers.get("Content-Length", 0))
        return json.loads(self.rfile.read(length)) if length else {}

    def do_GET(self):
        if self.path == "/api/login":
            self.send_redirect(OAUTH_AUTHORIZE_URL)

        elif self.path.startswith("/api/callback"):
            params = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            code = params.get("code", [None])[0]
            if not code:
                print(f"mod-manager: callback — no code in params: {params}")
                self.send_redirect("/")
                return
            print(f"mod-manager: callback — exchanging code...")
            token_data = exchange_code(code)
            if not token_data or "access_token" not in token_data:
                print(f"mod-manager: callback — token exchange failed: {token_data}")
                self.send_redirect("/")
                return
            print(f"mod-manager: callback — fetching discord user...")
            discord_user = fetch_discord_user(token_data["access_token"])
            if not discord_user or "id" not in discord_user:
                print(f"mod-manager: callback — user fetch failed: {discord_user}")
                self.send_redirect("/")
                return
            print(f"mod-manager: callback — login success: {discord_user.get('username')} ({discord_user['id']})")
            session_token = make_session(discord_user)
            self.send_redirect("/", headers={
                "Set-Cookie": f"session={session_token}; Path=/; HttpOnly; SameSite=Lax",
            })

        elif self.path == "/api/logout":
            cookie = SimpleCookie(self.headers.get("Cookie", ""))
            token = cookie.get("session")
            if token and token.value in SESSIONS:
                del SESSIONS[token.value]
            self.send_redirect("/", headers={
                "Set-Cookie": "session=; Path=/; HttpOnly; Max-Age=0",
            })

        elif self.path == "/api/session":
            session = self.get_session()
            if session:
                self.send_json({
                    "ok": True,
                    "username": session["username"],
                    "role": session["role"],
                    "avatar_url": session.get("avatar_url"),
                })
            else:
                self.send_json({"error": "no session"}, 401)

        elif self.path == "/api/mods":
            session = self.require_auth()
            if not session:
                return
            state = load_state()
            all_votes = get_all_discord_votes(state)
            mods = []
            for mod in state["mods"]:
                m = dict(mod)
                if isinstance(m.get("votes"), list):
                    m["votes"] = {u: 1 for u in m["votes"]}
                discord_voters = all_votes.get(mod.get("discord_msg_id"), set())
                m["voted_on_discord"] = session["discord_id"] in discord_voters
                m["discord_vote_count"] = len(discord_voters)
                mods.append(m)
            self.send_json(mods)

        elif self.path.startswith("/api/lookup/"):
            if not self.require_auth():
                return
            wid = self.path.split("/")[-1]
            self.send_json({"workshop_id": wid, "title": fetch_workshop_title(wid)})

        else:
            self.send_html()

    def do_POST(self):
        session = self.require_auth()
        if not session:
            return

        if self.path == "/api/mods":
            data = self.read_body()
            wid_match = re.search(r"id=(\d+)", data.get("workshop_id", ""))
            workshop_id = wid_match.group(1) if wid_match else data.get("workshop_id", "").strip()
            if not workshop_id or not workshop_id.isdigit():
                self.send_json({"error": "Ungültige Workshop ID"}, 400)
                return
            state = load_state()
            if any(m["workshop_id"] == workshop_id for m in state["mods"]):
                self.send_json({"error": "Mod bereits vorgeschlagen"}, 409)
                return
            title = fetch_workshop_title(workshop_id)
            mod = {
                "workshop_id": workshop_id,
                "title": title,
                "suggested_by": session["username"],
                "votes": {},
                "status": "suggested",
                "discord_msg_id": None,
            }
            state["mods"].append(mod)
            save_state(state)
            post_mod_to_discord(state, mod, "suggested")
            self.send_json({"ok": True})

        elif re.match(r"/api/mods/\d+/vote$", self.path):
            idx = int(self.path.split("/")[3])
            state = load_state()
            if 0 <= idx < len(state["mods"]):
                mod = state["mods"][idx]
                data = self.read_body()
                value = data.get("value", 0)
                if value not in (1, -1):
                    self.send_json({"error": "invalid vote"}, 400)
                    return
                if value == 1:
                    all_votes = get_all_discord_votes(state)
                    discord_voters = all_votes.get(mod.get("discord_msg_id"), set())
                    if session["discord_id"] in discord_voters:
                        self.send_json({"error": "Bereits auf Discord abgestimmt"}, 409)
                        return
                username = session["username"]
                if not isinstance(mod.get("votes"), dict):
                    mod["votes"] = {u: 1 for u in mod.get("votes", [])}
                current = mod["votes"].get(username, 0)
                if current == value:
                    del mod["votes"][username]
                else:
                    mod["votes"][username] = value
                save_state(state)
                post_mod_to_discord(state, mod, "voted")
                self.send_json({"ok": True})
            else:
                self.send_json({"error": "not found"}, 404)

        elif re.match(r"/api/mods/\d+/stage$", self.path):
            if session["role"] != "admin":
                self.send_json({"error": "Nur Admins können Mods genehmigen"}, 403)
                return
            idx = int(self.path.split("/")[3])
            data = self.read_body()
            new_status = data.get("status")
            if new_status not in ("approved", "rejected", "deleted"):
                self.send_json({"error": "invalid status"}, 400)
                return
            state = load_state()
            if 0 <= idx < len(state["mods"]):
                mod = state["mods"][idx]
                if new_status == "deleted":
                    thread_id = state.get("discord_thread_id")
                    msg_id = mod.get("discord_msg_id")
                    if thread_id and msg_id:
                        discord_api("DELETE", f"/channels/{thread_id}/messages/{msg_id}")
                    state["mods"].pop(idx)
                else:
                    mod["status"] = new_status
                    post_mod_to_discord(state, mod, new_status)
                save_state(state)
                sync_mods_txt(state)
                self.send_json({"ok": True})
            else:
                self.send_json({"error": "not found"}, 404)
        else:
            self.send_json({"error": "not found"}, 404)


if __name__ == "__main__":
    print(f"mod-manager: listening on port {PORT}")
    if MOD_MANAGER_ADMINS:
        print(f"mod-manager: admin discord IDs: {MOD_MANAGER_ADMINS}")
    else:
        print("mod-manager: WARNING — no MOD_MANAGER_ADMINS set, nobody can approve mods")
    HTTPServer(("0.0.0.0", PORT), Handler).serve_forever()
